[package]
name = "rust_blockchain_project"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2 = "0.10.6"
chrono = "0.4.35"

  #serde = { version = "1.0", features = ["derive"] }
  #tokio = { version = "1", features = ["full"] }