[package]
name = "rust_next_gen_ai"
version = "0.1.0"
edition = "2024"

[dependencies]
kalosm = { git = "https://github.com/floneum/floneum", version = "0.4.0", features = ["full"] }
tokio = { version = "1.47.1", features = ["full"] }
